### ISSUE TITLE
消息协议的 message 为何要放多个语义

### ISSUE THREAD

**Issue by Geno1024** [vertx-china/tree-new-bee#7]
> message除了可用String字符串类型以外，亦可使用Json Array和Json Object。
Json Array 可用来拼接不同的消息为一个消息

徒增协议解析复杂性
`message` 可能是一个消息，也可能是消息的集合
建议让每一个 key 的语义单一化

---

一个不一定可用的建议：
消息必然有一个 `messageType` 字段（可能就是你们的这个 `type`），然后根据这个字段判断具体的消息类型（纯文字？富文本？管理员控制类消息？批量转发？等等）

**Comment by Leibnizhu** [comment]
要统一下,最好有个公共sdk包 @chengenzhao

**Comment by chengenzhao** [comment]
客户端的环境不一样，sdk要提供很多种版本才行，这个不太现实
毕竟客户端有flutter有java还有kotlin
不仅语言不一样，发布的环境也不同
flutter用pub，java用maven central

至于type字段，这个目前也没法控制
事实上已经加入了type字段，但是基本上客户端和bot都没有积极响应
现有的客户端都还在用message和string这两个比较原始的类型上
所以定义type从目前的效果看，并不理想
shall v talk已经实现了带有type的json解析，其他客户端目前并未跟进
实际上type字段已经定义很久了，但是没有什么太大的进展

所以目前看，就直接判断是否含有message字段是最理想的
比较多客户端的开发采用了这个方式解析json
等什么时候type字段得到了比较多的反馈之后，再来推进也不迟
如果没有得到比较多的响应，那推进也没有什么意义
